enum ExposureStatusIndicatorSignalsEnum
{
    NOT_ANY_OPEN_POSITION,

    NOT_ANY_PLACED_ORDER,

    NOT_ANY_SELL_POSITIONS,

    NOT_ANY_BUY_POSITIONS,

    NOT_ANY_PLACED_BUY_LIMIT_ORDER,

    NOT_ANY_PLACED_SELL_LIMIT_ORDER,

    NOT_ANY_PLACED_BUY_STOP_ORDER,

    NOT_ANY_PLACED_SELL_STOP_ORDER,
}